/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertLineChart: typeof import('./../components/charts/AlertLineChart.vue')['default']
    AnimatedIconFrame: typeof import('./../components/common/AnimatedIconFrame.vue')['default']
    AppHeader: typeof import('./../components/common/AppHeader.vue')['default']
    BasePanel: typeof import('./../components/common/BasePanel.vue')['default']
    BottomNav: typeof import('./../components/common/BottomNav.vue')['default']
    CameraViewPanel: typeof import('./../components/panels/CameraViewPanel.vue')['default']
    Compass: typeof import('./../components/common/Compass.vue')['default']
    DeviceIconBase: typeof import('./../components/icons/DeviceIconBase.vue')['default']
    DeviceStatusPanel: typeof import('./../components/panels/DeviceStatusPanel.vue')['default']
    EnergyBarChart: typeof import('./../components/charts/EnergyBarChart.vue')['default']
    EnergyStatsPanel: typeof import('./../components/panels/EnergyStatsPanel.vue')['default']
    EnvLineChart: typeof import('./../components/charts/EnvLineChart.vue')['default']
    FloatingEntry: typeof import('./../components/common/FloatingEntry.vue')['default']
    FloorSelector: typeof import('./../components/common/FloorSelector.vue')['default']
    IconAccess: typeof import('./../components/icons/IconAccess.vue')['default']
    IconBroadcast: typeof import('./../components/icons/IconBroadcast.vue')['default']
    IconBuilding: typeof import('./../components/icons/IconBuilding.vue')['default']
    IconCamera: typeof import('./../components/icons/IconCamera.vue')['default']
    IconEnergy: typeof import('./../components/icons/IconEnergy.vue')['default']
    IconLighting: typeof import('./../components/icons/IconLighting.vue')['default']
    IconMeetingIdle: typeof import('./../components/icons/IconMeetingIdle.vue')['default']
    IconMeetingInUse: typeof import('./../components/icons/IconMeetingInUse.vue')['default']
    MapMarker: typeof import('./../components/common/MapMarker.vue')['default']
    MeetingListPanel: typeof import('./../components/panels/MeetingListPanel.vue')['default']
    MeetingStatsPanel: typeof import('./../components/panels/MeetingStatsPanel.vue')['default']
    MetricBlock: typeof import('./../components/common/MetricBlock.vue')['default']
    PanelTitle: typeof import('./../components/common/PanelTitle.vue')['default']
    ParkingPanel: typeof import('./../components/panels/ParkingPanel.vue')['default']
    PersonnelPanel: typeof import('./../components/panels/PersonnelPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsBar: typeof import('./../components/panels/StatsBar.vue')['default']
  }
}
